### ISSUE TITLE
Add numbers beside name to keep track of the number of people for each option

### ISSUE THREAD

**Issue by tshradheya** [whipermr5/countmeinbot#7]
Useful in cases when poll is used to decide which is the best date for meeting

**Comment by whipermr5** [comment]
Thanks for the contribution Shradheya! Do you think it might be cleaner to include the total count next to the topic heading instead of an index beside every name?

**Comment by tshradheya** [comment]
Agree.
Updated #8 as requested.

**Comment by whipermr5** [comment]
Deployed to App Engine; the change is live now :)

**Comment by tshradheya** [comment]
Thanks :)
